"""
Report generation and formatting.
Creates professional security reports in multiple formats.
"""

import json
from typing import Dict, Any
from datetime import datetime

from api_fortress.models import ScanResult, Severity


class ReportFormatter:
    """Premium report formatter for scan results."""

    def __init__(self, scan_result: ScanResult):
        self.result = scan_result

    def to_json(self, pretty: bool = True) -> str:
        """Generate JSON report."""
        report = {
            "scan_id": self.result.scan_id,
            "target": self.result.target,
            "scan_date": self.result.start_time.isoformat(),
            "duration": f"{self.result.duration:.2f}s" if self.result.duration else "N/A",
            "summary": {
                "total_requests": self.result.total_requests,
                "endpoints_tested": self.result.endpoints_tested,
                "vulnerabilities_found": len(self.result.vulnerabilities),
                "risk_score": self.result.get_risk_score(),
                "severity_breakdown": self.result.get_severity_counts(),
            },
            "vulnerabilities": [
                {
                    "id": v.id,
                    "name": v.name,
                    "type": v.type,
                    "severity": v.severity,
                    "endpoint": v.endpoint,
                    "method": v.method,
                    "description": v.description,
                    "evidence": v.evidence,
                    "remediation": v.remediation,
                    "cwe_id": v.cwe_id,
                    "cvss_score": v.cvss_score,
                    "timestamp": v.timestamp.isoformat(),
                }
                for v in self.result.vulnerabilities
            ],
        }

        if pretty:
            return json.dumps(report, indent=2, ensure_ascii=False)
        return json.dumps(report, ensure_ascii=False)

    def to_markdown(self) -> str:
        """Generate Markdown report."""
        md = f"""# 🏰 API Fortress Security Report

## Scan Summary

- **Scan ID**: `{self.result.scan_id}`
- **Target**: `{self.result.target}`
- **Date**: {self.result.start_time.strftime('%Y-%m-%d %H:%M:%S')}
- **Duration**: {self.result.duration:.2f}s
- **Total Requests**: {self.result.total_requests}
- **Endpoints Tested**: {self.result.endpoints_tested}

## Risk Assessment

**Overall Risk Score**: {self.result.get_risk_score():.1f}/100

### Vulnerability Breakdown

"""
        severity_counts = self.result.get_severity_counts()
        for severity in ["critical", "high", "medium", "low", "info"]:
            count = severity_counts.get(severity, 0)
            emoji = self._get_severity_emoji(severity)
            md += f"- {emoji} **{severity.upper()}**: {count}\n"

        md += f"\n**Total Vulnerabilities**: {len(self.result.vulnerabilities)}\n\n"

        if self.result.vulnerabilities:
            md += "## Detailed Findings\n\n"

            for i, vuln in enumerate(self.result.vulnerabilities, 1):
                emoji = self._get_severity_emoji(vuln.severity.lower())
                md += f"### {i}. {emoji} {vuln.name}\n\n"
                md += f"- **Severity**: {vuln.severity}\n"
                md += f"- **Type**: {vuln.type}\n"
                md += f"- **Endpoint**: `{vuln.endpoint}`\n"
                md += f"- **Method**: `{vuln.method}`\n"

                if vuln.cwe_id:
                    md += f"- **CWE**: [{vuln.cwe_id}](https://cwe.mitre.org/data/definitions/{vuln.cwe_id.replace('CWE-', '')}.html)\n"
                if vuln.cvss_score:
                    md += f"- **CVSS Score**: {vuln.cvss_score}\n"

                md += f"\n**Description**: {vuln.description}\n\n"

                if vuln.evidence:
                    md += f"**Evidence**:\n```\n{vuln.evidence}\n```\n\n"

                if vuln.remediation:
                    md += "**Remediation**:\n"
                    for step in vuln.remediation:
                        md += f"- {step}\n"
                    md += "\n"

                md += "---\n\n"

        md += """## Recommendations

1. **Immediate Actions**:
   - Address all CRITICAL and HIGH severity vulnerabilities
   - Review and implement recommended mitigations
   - Conduct additional testing after fixes

2. **Long-term Improvements**:
   - Implement security testing in CI/CD pipeline
   - Regular security audits and penetration testing
   - Security training for development team
   - Establish secure coding standards

---

*Generated by API Fortress v1.0.0*
"""

        return md

    def to_html(self) -> str:
        """Generate HTML report."""
        severity_counts = self.result.get_severity_counts()

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>API Fortress Security Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 40px 20px;
            color: #333;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 40px;
            text-align: center;
        }}
        .header h1 {{
            font-size: 2.5em;
            margin-bottom: 10px;
        }}
        .content {{
            padding: 40px;
        }}
        .summary-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin: 30px 0;
        }}
        .summary-card {{
            background: #f8f9fa;
            padding: 25px;
            border-radius: 12px;
            border-left: 4px solid #667eea;
        }}
        .summary-card h3 {{
            color: #667eea;
            font-size: 0.9em;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
        }}
        .summary-card .value {{
            font-size: 2em;
            font-weight: bold;
            color: #333;
        }}
        .severity-badges {{
            display: flex;
            gap: 15px;
            flex-wrap: wrap;
            margin: 30px 0;
        }}
        .badge {{
            padding: 10px 20px;
            border-radius: 25px;
            font-weight: bold;
            font-size: 0.9em;
        }}
        .badge.critical {{ background: #dc3545; color: white; }}
        .badge.high {{ background: #fd7e14; color: white; }}
        .badge.medium {{ background: #ffc107; color: #333; }}
        .badge.low {{ background: #17a2b8; color: white; }}
        .badge.info {{ background: #6c757d; color: white; }}
        .vulnerability {{
            background: #f8f9fa;
            border-radius: 12px;
            padding: 25px;
            margin: 20px 0;
            border-left: 4px solid #667eea;
        }}
        .vulnerability.critical {{ border-left-color: #dc3545; }}
        .vulnerability.high {{ border-left-color: #fd7e14; }}
        .vulnerability.medium {{ border-left-color: #ffc107; }}
        .vulnerability.low {{ border-left-color: #17a2b8; }}
        .vulnerability h3 {{
            color: #333;
            margin-bottom: 15px;
        }}
        .vuln-meta {{
            display: flex;
            gap: 20px;
            margin: 15px 0;
            font-size: 0.9em;
        }}
        .vuln-meta span {{
            background: white;
            padding: 5px 12px;
            border-radius: 6px;
        }}
        pre {{
            background: #2d2d2d;
            color: #f8f8f2;
            padding: 15px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 15px 0;
        }}
        .remediation {{
            background: #d4edda;
            border: 1px solid #c3e6cb;
            border-radius: 8px;
            padding: 15px;
            margin: 15px 0;
        }}
        .remediation h4 {{
            color: #155724;
            margin-bottom: 10px;
        }}
        .remediation ul {{
            margin-left: 20px;
        }}
        .remediation li {{
            margin: 8px 0;
            color: #155724;
        }}
        .footer {{
            text-align: center;
            padding: 30px;
            color: #666;
            background: #f8f9fa;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🏰 API Fortress</h1>
            <p>Professional Security Assessment Report</p>
        </div>

        <div class="content">
            <h2>Scan Summary</h2>
            <div class="summary-grid">
                <div class="summary-card">
                    <h3>Target</h3>
                    <div class="value" style="font-size: 1.2em;">{self.result.target}</div>
                </div>
                <div class="summary-card">
                    <h3>Risk Score</h3>
                    <div class="value">{self.result.get_risk_score():.1f}/100</div>
                </div>
                <div class="summary-card">
                    <h3>Total Requests</h3>
                    <div class="value">{self.result.total_requests}</div>
                </div>
                <div class="summary-card">
                    <h3>Endpoints Tested</h3>
                    <div class="value">{self.result.endpoints_tested}</div>
                </div>
            </div>

            <h3>Vulnerability Distribution</h3>
            <div class="severity-badges">
                <span class="badge critical">CRITICAL: {severity_counts.get('critical', 0)}</span>
                <span class="badge high">HIGH: {severity_counts.get('high', 0)}</span>
                <span class="badge medium">MEDIUM: {severity_counts.get('medium', 0)}</span>
                <span class="badge low">LOW: {severity_counts.get('low', 0)}</span>
            </div>

            <h2>Detailed Findings ({len(self.result.vulnerabilities)} vulnerabilities)</h2>
"""

        for i, vuln in enumerate(self.result.vulnerabilities, 1):
            severity_class = vuln.severity.lower()
            html += f"""
            <div class="vulnerability {severity_class}">
                <h3>{i}. {vuln.name}</h3>
                <div class="vuln-meta">
                    <span><strong>Severity:</strong> {vuln.severity}</span>
                    <span><strong>Type:</strong> {vuln.type}</span>
                    <span><strong>Method:</strong> {vuln.method}</span>
                </div>
                <p><strong>Endpoint:</strong> <code>{vuln.endpoint}</code></p>
                <p><strong>Description:</strong> {vuln.description}</p>
"""

            if vuln.evidence:
                html += f'<pre>{vuln.evidence}</pre>'

            if vuln.remediation:
                html += '<div class="remediation"><h4>🛡️ Remediation Steps</h4><ul>'
                for step in vuln.remediation:
                    html += f'<li>{step}</li>'
                html += '</ul></div>'

            html += '</div>'

        html += """
        </div>

        <div class="footer">
            <p>Generated by <strong>API Fortress v1.0.0</strong></p>
            <p>Professional API Security Testing Suite</p>
        </div>
    </div>
</body>
</html>"""

        return html

    def _get_severity_emoji(self, severity: str) -> str:
        """Get emoji for severity level."""
        emojis = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🔵",
            "info": "⚪",
        }
        return emojis.get(severity.lower(), "⚪")
